### ISSUE TITLE
Scanner 'undefined'

### ISSUE THREAD

**Issue by sadsad1314** [rKv4dr4t/Triangular_Arbitrage#1]
`
found 0 vulnerabilities

C:\Users\user\Desktop\Triangular_Arbitrage-main\scannerNode>node app.js
Scanner starting...
Scanner ready
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined`
Is this how scanner working or it should works as the Karthik's scanner?

**Comment by rKv4dr4t** [comment]
After you run scannerNode you have to run also sendOrders app. Until sendOrders is not run, scannerNode will show you undefined results
